apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-a
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: mgmt
    repoURL: 'https://github.com/duffleit/decentralized-platform.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - platform-team-a.yaml
  project: default