apiVersion: v1
kind: Namespace
metadata:
  name: strimzi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: strimzi-quota
  namespace: strimzi
spec:
  hard:
    pods: '10'
    requests.cpu: '1'
    requests.memory: 1Gi
    limits.cpu: '2'
    limits.memory: 4Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: strimzi-limitrange
  namespace: strimzi
spec:
  limits:
    - default:
        memory: 512Mi
        cpu: 500m
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      type: Container